### ISSUE TITLE
revised version 0.6

### ISSUE THREAD

**Issue by IrinaDornblut** [opengeospatial/HY_Features#174]
Revised version 0.6:  some open issues fixed  in text and figures (changes in figures accepted):

- [x] Fix up river reference system in 6.4 (todo: new diagram 15) #163 
- [x] HY_Features vs. Hydro Feature schema #170 
- [x] Junction vs. node #148 
- [x] ‘ISO model not imported’ clarified in text 
- [x] Constraints on dendritic catchment in fig 8 #161 
- [x] Uml enlarged in embedded figs 7,8,9,10,11,13,14 #169 
- [x] shape of waterEdge – figs updated 
- [x] terms: hydrography- fixed #173 
- [x] American writing in uml model (uml annotations aligned to spec doc 
- [x] spell- check in spec doc (complete spec doc in American writing
- [x] All Figures checked and updated if needed
- [x] New figure for complex topology per #160 
- [x] Clarify why only application schema modules appear in conformance classes per #165 ?
- [x] Add back a third pane in figure 12 per #162 
- [x] Potentially add a figure (13?) to show dendritic, non-dendritic, and interior catchments. #164  

see: https://github.com/opengeospatial/HY_Features/blob/master/reference_documents/14-111r2_v06_20160906_ID.docx
